version: "3.9"

services:

  users_service:
    build:
      context: .
      dockerfile: ./services/users_service/Dockerfile
    container_name: users_service
    ports:
      - "5001:5001"

  rooms_service:
    build:
      context: .
      dockerfile: ./services/rooms_service/Dockerfile
    container_name: rooms_service
    ports:
      - "5002:5002"

  bookings_service:
    build:
      context: .
      dockerfile: ./services/bookings_service/Dockerfile
    container_name: bookings_service
    ports:
      - "5003:5003"

  reviews_service:
    build:
      context: .
      dockerfile: ./services/reviews_service/Dockerfile
    container_name: reviews_service
    ports:
      - "5004:5004"
